"行番号表示
set number
"シンタックスハイライト
syntax on
"マウススクロール
set mouse=a 
"ヤンクでクリップボード使用
set clipboard=unnamed,autoselect
"colorschme
set termguicolors
set background=light
colorscheme iceberg
" Tab入力時にをスペース挿入
set expandtab
" Tabの幅を設定
set shiftwidth=2
set softtabstop=2
set tabstop=2
"自動インデントを無効化
set noautoindent
" netrwを有効化
"filetype plugin on
"折り返さない
set nowrap
" lightline
set laststatus=2
set cursorline
set cursorcolumn

" complete
set completeopt=menuone,noselect

" plugin manager
call plug#begin()
  Plug 'lambdalisue/fern.vim'
  Plug 'lambdalisue/nerdfont.vim'
  Plug 'lambdalisue/fern-renderer-nerdfont.vim'
  Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
  Plug 'mattn/vim-sonictemplate'
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'junegunn/fzf.vim'
  Plug 'prabirshrestha/asyncomplete.vim'
  Plug 'prabirshrestha/asyncomplete-lsp.vim'
  Plug 'prabirshrestha/vim-lsp'
  Plug 'mattn/vim-lsp-settings'
  Plug 'mattn/vim-lsp-icons'
  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'
  Plug 'evanleck/vim-svelte'
  Plug 'lifepillar/vim-colortemplate'
call plug#end()

" 各種設定の読み込み
call map(sort(split(globpath(&runtimepath, '_config/*.vim'))), {->[execute('exec "so" v:val')]})
